//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numerics_Realtime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Numerics_Realtime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017-01-01   997.6888
        ///2017-01-02  1018.0500
        ///2017-01-03  1030.8175
        ///2017-01-04  1129.8700
        ///2017-01-05  1005.8150
        ///2017-01-06   895.6700
        ///2017-01-07   905.1700
        ///2017-01-08   913.5238
        ///2017-01-09   899.3500
        ///2017-01-10   904.7925
        ///2017-01-11   775.9813
        ///2017-01-12   802.8288
        ///2017-01-13   826.1213
        ///2017-01-14   818.6388
        ///2017-01-15   822.4225
        ///2017-01-16   830.2638
        ///2017-01-17   904.4538
        ///2017-01-18   884.2513
        ///2017-01-19   898.0213
        ///2017-01-20   891.6238
        ///2017-01-21   920.0113
        ///2017-01-22   925.3313
        ///2017-0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Data_Samples {
            get {
                return ResourceManager.GetString("Data_Samples", resourceCulture);
            }
        }

        public static string Data_FactoryProcess
        {
            get
            {
                return ResourceManager.GetString("continuous_factory_process", resourceCulture);
            }
        }

    }
}
