//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numerics_TeeChart.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Numerics_TeeChart.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp,L_1,L_2,A_1,A_2,B_1,B_2,C_1,C_2,A_3,A_4,B_3,B_4,C_3,C_4,L_3,L_4,L_5,L_6,L_7,L_8,L_9,L_10,A_5,B_5,C_5
        ///0,-20.774487463165073,-39.356281846192935,-77.97088192608473,-83.05907034608407,-100.0,-100.0,-96.07019445824503,-98.82036830774163,-53.77219508584044,-65.76505739810617,-84.04977375469167,-86.63506384286273,-31.495738256109085,-48.20885800803449,-97.98956964519041,-22.58212496320475,-41.391447605443346,-82.68675858040388,-22.19053052651033,-4.735419099113209,-22.223065829681445,-44.56905339753232, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string C8 {
            get {
                return ResourceManager.GetString("C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time_stamp,AmbientConditions.AmbientHumidity.U.Actual,AmbientConditions.AmbientTemperature.U.Actual,Machine1.RawMaterial.Property1,Machine1.RawMaterial.Property2,Machine1.RawMaterial.Property3,Machine1.RawMaterial.Property4,Machine1.RawMaterialFeederParameter.U.Actual,Machine1.Zone1Temperature.C.Actual,Machine1.Zone2Temperature.C.Actual,Machine1.MotorAmperage.U.Actual,Machine1.MotorRPM.C.Actual,Machine1.MaterialPressure.U.Actual,Machine1.MaterialTemperature.U.Actual,Machine1.ExitZoneTemperature.C.Actual,Mac [rest of string was truncated]&quot;;.
        /// </summary>
        public static string continuous_factory_process {
            get {
                return ResourceManager.GetString("continuous_factory_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context
        ///This data was taken from an actual production line near Detroit, Michigan. The goal is to predict certain properties of the line&apos;s output from the various input data. The line is a high-speed, continuous manufacturing process with parallel and series stages.
        ///
        ///Content
        ///The data comes from one production run spanning several hours. Liveline Technologies has a large quantity of this type of data from multiple production lines in various locations.
        ///
        ///Acknowledgements
        ///The Liveline team would like to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string continuous_factory_process1 {
            get {
                return ResourceManager.GetString("continuous_factory_process1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017-01-01   997.6888
        ///2017-01-02  1018.0500
        ///2017-01-03  1030.8175
        ///2017-01-04  1129.8700
        ///2017-01-05  1005.8150
        ///2017-01-06   895.6700
        ///2017-01-07   905.1700
        ///2017-01-08   913.5238
        ///2017-01-09   899.3500
        ///2017-01-10   904.7925
        ///2017-01-11   775.9813
        ///2017-01-12   802.8288
        ///2017-01-13   826.1213
        ///2017-01-14   818.6388
        ///2017-01-15   822.4225
        ///2017-01-16   830.2638
        ///2017-01-17   904.4538
        ///2017-01-18   884.2513
        ///2017-01-19   898.0213
        ///2017-01-20   891.6238
        ///2017-01-21   920.0113
        ///2017-01-22   925.3313
        ///2017-0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Data_Samples {
            get {
                return ResourceManager.GetString("Data_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Plant Data for Condition Monitoring
        ///Prediction of the condition of an important component
        ///
        ///Description
        ///Context
        ///This dataset was used in previous research projects, for example in IMPROVE.
        ///
        ///We ony use C8 Data in this demo.
        ///
        ///Content
        ///The use case focuses on the prediction of the condition of an important component within production lines.
        ///The condition of this component is important for the function of the plant and the resulting product quality.
        ///Data for 8 run-to-failure experiments wer [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Production_Plant_Data_for_Condition_Monitoring {
            get {
                return ResourceManager.GetString("Production_Plant_Data_for_Condition_Monitoring", resourceCulture);
            }
        }
    }
}
